employee.all=SELECT * FROM hs_hr_employee
employee.by.number=SELECT * FROM hs_hr_employee WHERE emp_number=?
employee.by.number.and.firstname=SELECT * FROM hs_hr_employee WHERE emp_number=? AND emp_firstname=?
employee.by.firstname=SELECT * FROM hs_hr_employee WHERE emp_firstname=?
employee.count=SELECT COUNT(*) FROM hs_hr_employee